[repo]
url = "https://github.com/doda-s/nippon-ten.git"

[feature-flags]
performance = true

[performance] # Performance Test
# Example: ["/api/endpoint1", "/api/endpoint2"]
api-endpoints = ["/hello"]
api-url = "localhost:8080"
application-type = "quarkus"